apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/tim.c/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 09 Aug 2025 10:16:39 KST
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: cluster_info
    server: https://127.0.0.1:49938
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 09 Aug 2025 10:16:39 KST
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/tim.c/.minikube/profiles/minikube/client.crt
    client-key: /Users/tim.c/.minikube/profiles/minikube/client.key
