logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    io.codeclick.platform.config.debug.DebugFilter: INFO
    org.springframework.web.filter.GenericFilterBean: INFO
    org.springframework.web.client.RestTemplate: INFO
    reactor.netty.http.client: INFO

spring:
  #lookup third party server
  rabbitmq:
    host: 10.202.25.216
    port: 5672
    virtual-host: /${spring.application.name}
    username: ${spring.application.name}
    # TODO: encrypt
    password: platform!#%135
    addresses: ${QUEUE_ADDRESSES:10.202.25.216:5672}
    address-shuffle-mode: random

  security:
    debug: true
    oauth2:
      client:
        registration:
          kakao-bizmsg:
            authorization-grant-type: client_credentials
            client-id: RCDKCI0000
            client-secret: RCDKCI0000_FdZGtR0uTcecOX7PVwVW+g
            scope:
              - read
              - write
          kakao-template:
            authorization-grant-type: client_credentials
            client-id: RCDKCI0000_001
            client-secret: RCDKCI0000_DGGMsl6CR8S+UJLjpoHKUQ
            scope:
              - read
              - write
          kakao-sync:
            authorization-grant-type: authorization_code
            client-id: 4685173414465be4d355d1a205ef52ad
            client-secret: cK4Um8RpUIc7KIreVG5DULdRKJIqOvnE
            redirect-uri: ${KAKAO_SYNC_RETURN_URL:https://always-talk.kakaoiconnect.ai/portal/api/v1/auth/authorized}
            scope:
              - read
              - write
        provider:
          kakao-bizmsg:
            token-uri: https://web1.dktechinmsg.com/v1/oauth/token
          kakao-template:
            token-uri: https://web1.dktechinmsg.com/mng/v1/oauth/token
          kakao-sync:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  redis:
    host: 10.202.25.216
    port: 6379
    password: ${REDIS_PASSWORD:}
    cluster:
      nodes:

application:
  platform:
    whitelist:
      - 203.133.162.196
      - 127.0.0.1
    platforms:
      kakao_alert_talk:
        api-base-url: https://bizmsg-web.kakaoenterprise.com
        api-key: ${KAKAO_BIZ_API_KEY:1234}
      kakao_friend_talk:
        api-base-url: https://bizmsg-web.kakaoenterprise.com
        api-key: ${KAKAO_BIZ_API_KEY:1234}
      kakao_template:
        api-base-url: https://bizmsg-web.kakaoenterprise.com
        api-key: ${KAKAO_BIZ_API_KEY:1234}
serviceIdKey:
  always: /open/@mtk27zwymtu3oou?extra=

#Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**