# Local Dev 환경에서 Redis를 Standalone으로 사용하기에 해당 옵션은 주석 처리
# spring:
#  redis:
#    cluster:
#      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    io.codeclick.platform.config.debug.DebugFilter: DEBUG
    org.springframework.web.filter.GenericFilterBean: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  #lookup third party server
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /${spring.application.name}
    username: ${spring.application.name}
    # TODO: encrypt
    password: platform!#%135
    addresses: ${QUEUE_ADDRESSES:127.0.0.1:5672,localhost:5672}
    address-shuffle-mode: random

  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}
    cluster:
      nodes:

application:
  platform:
    platforms:
      kakao_alert_talk:
        api-base-url: https://bzm-api.kakao.com
        api-key: ${KAKAO_BIZ_API_KEY:aedfb3082a49eb15cbcfa6f4a87927816573b071}
#        api-base-url: https://web1.dktechinmsg.com
#        api-key: ${KAKAO_BIZ_API_KEY:1234}
      kakao_friend_talk:
        api-base-url: https://bzm-api.kakao.com
        api-key: ${KAKAO_BIZ_API_KEY:aedfb3082a49eb15cbcfa6f4a87927816573b071}
#        api-base-url: https://web1.dktechinmsg.com
#        api-key: ${KAKAO_BIZ_API_KEY:1234}
      kakao_template:
        api-base-url: https://bzm-center.kakao.com/api
        api-key: ${KAKAO_BIZ_API_KEY:aedfb3082a49eb15cbcfa6f4a87927816573b071}
serviceIdKey:
  bnk: /open/@mtk27zwymtu3oou?extra=

#Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**