spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            portal-service:
              - uri: http://localhost:8080/portal
              - uri: http://127.0.0.1:8080/portal

  security:
    debug: true
    oauth2:
      client:
        registration:
          kakao-bizmsg:
            authorization-grant-type: client_credentials
            client-id: R000000071
            client-secret: R000000071_uFkrhKtpTVeca4fZnn2GiA
            scope:
              - read
              - write
          kakao-template:
            authorization-grant-type: client_credentials
            client-id: R000000071
            client-secret: R000000071_uFkrhKtpTVeca4fZnn2GiA
            scope:
              - read
              - write
          kakao-sync:
            authorization-grant-type: authorization_code
            client-id: 5c3a2963a9a33c85427b040b76d55c5b
            client-secret: 5c3a2963a9a33c85427b040b76d55c5b
            redirect-uri: ${KAKAO_SYNC_RETURN_URL:https://kep-talk2.codeclick.co.kr/platform/auth/kakao-sync/code}
            scope:
              - read
              - write
        provider:
          kakao-bizmsg:
            token-uri: https://bizmsg-web.kakaoenterprise.com/v1/oauth/token
          kakao-template:
            token-uri: https://bizmsg-web.kakaoenterprise.com/mng/v1/oauth/token
          kakao-sync:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  file:
    path: ${LOGGING_PATH:/opt/storage/logs}/kep-talk/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
