spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            portal-service:
              - uri: http://localhost:8080/portal
              - uri: http://127.0.0.1:8080/portal

  #lookup third party server
  rabbitmq:
    host: 10.206.16.58
    port: 5672
    virtual-host: /${spring.application.name}
    username: ${spring.application.name}
    # TODO: encrypt
    password: platform!#%135
    addresses: ${QUEUE_ADDRESSES:10.206.16.58:5672,10.206.16.58:5672}
    address-shuffle-mode: random

  redis:
    host: 10.206.16.58
    port: 6379
    password: ${REDIS_PASSWORD:}
    cluster:
      nodes:

logging:
  file:
    path: ${LOGGING_PATH:/opt/storage/logs}/always/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7

application:
  platform:
    whitelist:
      - 192.168.0/24
      - 127.0.0.1
      - ::1
      - 0:0:0:0:0:0:0:1
      - 113.29.189.174
      - 113.29.189.176
      - 10.100.0.193
      - 61.109.236.74
      - 10.182.100.179
      - 203.133.162.185
      - 203.133.162.195
      - 203.133.162.196
    platforms:
      kakao_alert_talk:
        api-base-url: https://bizmsg-web.kakaoenterprise.com
        api-key: ${KAKAO_BIZ_API_KEY:1234}
      kakao_friend_talk:
        api-base-url: https://bizmsg-web.kakaoenterprise.com
        api-key: ${KAKAO_BIZ_API_KEY:1234}
      kakao_template:
        api-base-url: https://bizmsg-web.kakaoenterprise.com
        api-key: ${KAKAO_BIZ_API_KEY:1234}
serviceIdKey:
  bnk: /open/@mtk27zwymtu3oou?extra=

#Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**