spring:
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false
        simple:
          instances:
            portal-service:
              - uri: http://localhost:8080/portal
              - uri: http://127.0.0.1:8080/portal
            talk-service:
              - uri: http://172.17.0.3:8090/talk
              - uri: http://172.17.0.3:8090/talk

  security:
    debug: true
    oauth2:
      client:
        registration:
          kakao-bizmsg:
            authorization-grant-type: client_credentials
            client-id: RCDKCI0000
            client-secret: RCDKCI0000_FdZGtR0uTcecOX7PVwVW+g
            scope:
              - read
              - write
          kakao-template:
            authorization-grant-type: client_credentials
            client-id: RCDKCI0000_001
            client-secret: RCDKCI0000_DGGMsl6CR8S+UJLjpoHKUQ
            scope:
              - read
              - write
          kakao-sync:
            authorization-grant-type: authorization_code
            client-id: 4685173414465be4d355d1a205ef52ad
            client-secret: cK4Um8RpUIc7KIreVG5DULdRKJIqOvnE
            redirect-uri: ${KAKAO_SYNC_RETURN_URL:https://always-talk.kakaoiconnect.ai/portal/api/v1/auth/authorized}
            scope:
              - read
              - write
        provider:
          kakao-bizmsg:
            token-uri: https://web1.dktechinmsg.com/v1/oauth/token
          kakao-template:
            token-uri: https://web1.dktechinmsg.com/mng/v1/oauth/token
          kakao-sync:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  #lookup third party server
  rabbitmq:
    host: 10.206.16.58
#    host: 10.111.25.211
    port: 5672
    virtual-host: /${spring.application.name}
    username: ${spring.application.name}
    # TODO: encrypt
    password: platform!#%135
#    addresses: ${QUEUE_ADDRESSES:10.111.25.211:5672,10.111.25.211:5672}
    addresses: ${QUEUE_ADDRESSES:10.206.16.58:5672,10.206.16.58:5672}
    address-shuffle-mode: random

  redis:
    host: 10.206.16.58
#    host: 10.111.25.211
    port: 6379
    password: ${REDIS_PASSWORD:}
    cluster:
      nodes:

logging:
  file:
    path: ${LOGGING_PATH:/opt/storage/logs}/always/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7

application:
  platform:
    whitelist:
      - 192.168.0/24
      - 127.0.0.1
      - ::1
      - 0:0:0:0:0:0:0:1
      - 10.182.100.179
      - 203.133.162.185
      - 203.133.162.195
      - 203.133.162.196
      - 10.100.0.193
    platforms:
      kakao_alert_talk:
        api-base-url: https://bzm-api.kakao.com
        api-key: ${KAKAO_BIZ_API_KEY:aedfb3082a49eb15cbcfa6f4a87927816573b071}
      kakao_friend_talk:
        api-base-url: https://bzm-api.kakao.com
        api-key: ${KAKAO_BIZ_API_KEY:aedfb3082a49eb15cbcfa6f4a87927816573b071}
      kakao_template:
        api-base-url: https://bzm-center.kakao.com/api
        api-key: ${KAKAO_BIZ_API_KEY:aedfb3082a49eb15cbcfa6f4a87927816573b071}
serviceIdKey:
  always: /@ntezrdc3njvlvcb

#Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**