{{- $ns := .Release.Namespace -}}
{{- range $app := .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.service.name }}
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ $app.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ $app.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ $app.service.port }}
---
{{- end }}
