namespace: sbox

image:
  # Docker Hub 레지스트리
  registry: docker.io/timulys
  pullPolicy: IfNotPresent

# Secret 이름들 (이미 sbox에 생성됨)
secrets:
  rabbitmq: rabbitmq-cred
  redis: redis-cred
  mysql: mysql-cred

# Ingress는 이미 사용된 것을 활용
ingress:
  enabled: false
  
# 앱 목록
apps:
  - name: platform
    replicaCount: 3
    image:
      name: platform
      tag: platform-abc123   # 실제 빌드된 이미지 태그로 변경
    service:
      name: platform-service
      port: 8080
    contextPath: /platform
    env:
      SPRING_PROFILES_ACTIVE: sandbox
    resources: {}
    probes:
      path: /platform/actuator/health

  - name: portal
    replicaCount: 3
    image:
      name: portal
      tag: portal-abc123     # 실제 빌드된 이미지 태그로 변경
    service:
      name: portal-service
      port: 8080
    contextPath: /portal
    env:
      SPRING_PROFILES_ACTIVE: sandbox
    resources: {}
    probes:
      path: /portal/actuator/health

  - name: talk
    replicaCount: 3
    image:
      name: talk
      tag: talk-abc123       # 실제 빌드된 이미지 태그로 변경
    service:
      name: talk-service
      port: 8080
    contextPath: /talk
    env:
      SPRING_PROFILES_ACTIVE: sandbox
    resources: {}
    probes:
      path: /talk/actuator/health
