namespace: sbox
image:
  # Docker Hub 레지스트리
  registry: docker.io/timulys
  pullPolicy: IfNotPresent
# Secret 이름들 (이미 sbox에 생성됨)
secrets:
  rabbitmq: rabbitmq-cred
  redis: redis-cred
# Ingress는 이미 사용된 것을 활용
ingress:
  enabled: false
# 앱 목록
apps:
  - name: platform
    replicaCount: 3
    image:
      name: platform
      tag: 'platform-f0207a8'
    service: {name: platform-service, port: 8080}
    contextPath: /platform
    env: {SPRING_PROFILES_ACTIVE: sandbox}
    resources: {}
    probes:
      path: "/" # actuator 없으면 200 주는 경로
      readinessInitialDelay: 60
      livenessInitialDelay: 180
      readinessPeriod: 10
      livenessPeriod: 10
      readinessTimeout: 5
      livenessTimeout: 5
      readinessFailures: 6
      livenessFailures: 6
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
    extraEnv:
      - name: JAVA_TOOL_OPTIONS
        value: >
          -XX:+UnlockExperimentalVMOptions
          -XX:+UseCGroupMemoryLimitForHeap
          -Xms512m -Xmx512m
          -XX:MaxMetaspaceSize=128m
          -XX:+ExitOnOutOfMemoryError
          -Xss256k
    
  - name: portal
    replicaCount: 3
    image:
      name: portal
      tag: 'portal-f2e0087'
    service: {name: portal-service, port: 8080}
    contextPath: /portal
    env: {SPRING_PROFILES_ACTIVE: sandbox}
    resources: {}
    probes:
      path: "/" # actuator 없으면 200 주는 경로
      readinessInitialDelay: 60
      livenessInitialDelay: 180
      readinessPeriod: 10
      livenessPeriod: 10
      readinessTimeout: 5
      livenessTimeout: 5
      readinessFailures: 6
      livenessFailures: 6
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
    extraEnv:
      - name: JAVA_TOOL_OPTIONS
        value: >
          -XX:+UnlockExperimentalVMOptions
          -XX:+UseCGroupMemoryLimitForHeap
          -Xms512m -Xmx512m
          -XX:MaxMetaspaceSize=128m
          -XX:+ExitOnOutOfMemoryError
          -Xss256k
          
  - name: talk
    replicaCount: 3
    image:
      name: talk
      tag: 'talk-64729fe'
    service: {name: talk-service, port: 8080}
    contextPath: /talk
    env: {SPRING_PROFILES_ACTIVE: sandbox}
    resources: {}
    probes:
      path: "/" # actuator 없으면 200 주는 경로
      readinessInitialDelay: 60
      livenessInitialDelay: 180
      readinessPeriod: 10
      livenessPeriod: 10
      readinessTimeout: 5
      livenessTimeout: 5
      readinessFailures: 6
      livenessFailures: 6
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    extraEnv:
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=60 -XX:InitialRAMPercentage=20 -XX:+ExitOnOutOfMemoryError -Xss256k"
