debug: false
spring:
  application:
    name: legacy
  profiles:
    active: local
  mvc:
    throwExceptionIfNoHandlerFound: true
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations:
#        - classpath:/META-INF/resources/
#        - classpath:/resources/
#        - classpath:/static/
#        - classpath:/public/
#        - file:{$STORAGE_PATH:/opt/storage/}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jmx:
    enabled: false
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    add-properties: false
  thymeleaf:
    cache: true

  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false
        simple:
          instances:
            portal-service:
              - uri: http://localhost:8090/portal
              - uri: http://127.0.0.1:8090/portal
    loadbalancer:
      health-check:
        path:
          default: /actuator/health
        interval: 10000
      retry:
        enabled: true
        max-retries-on-next-service-instance: 1
        max-retries-on-same-service-instance: 0
        retryable-status-codes: 404, 503
        backoff:
          enabled: true
          jitter: 0.5

  datasource:
    hikari:
      maximum-pool-size: 5
  sql:
    init:
      mode: never
      platform: h2
      schema-locations: classpath*:db/${spring.sql.init.platform}/schema.sql
      data-locations: classpath*:db/${spring.sql.init.platform}/data.sql

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    bean: propertyEncryptor

logging:
  pattern:
    console: '%(%d{yyyy-MM-dd HH:mm:ss} %30.30logger:%-4line) %-5level > %msg\n'
  level:
    root: info

server:
  port: ${SERVER_PORT:8001}
  servlet:
    context-path: /${spring.application.name}
  error:
    whitelabel:
      enabled: false
    include-exception: true

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

application:
  core:
    portal-service-uri: http://portal-service/portal
    whitelist:
      - 192.168.0/24
      - 127.0.0.1
      - ::1
      - 0:0:0:0:0:0:0:1
  portal:
    api-base-path: /api/v1
