spring:
  config:
    import:
      - optional:./portal-dev.yml
      - optional:./mysql-dev.yml

  security:
    debug: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    add-properties: true
  thymeleaf:
    cache: false

  cloud:
    discovery:
      client:
        simple:
          instances:
            platform-service:
              - uri: http://localhost:8080/platform
              - uri: http://127.0.0.1:8080/platform
            legacy-service:
              - uri: http://localhost:8080/legacy
              - uri: http://localhost:8080/legacy

  rabbitmq:
    host: localhost
    port: 5672

  redis:
#    host: 10.182.100.199
    host: localhost
    port: 6379

logging:
  pattern:
    file: '%(%d{yyyy-MM-dd HH:mm:ss} %30.30logger:%-4line) %-5level > %msg\n'
  file:
    path: ${LOGGING_PATH:/opt/storage/logs}/always/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  level:
    root: info
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    jdbc.sqlonly: debug
    jdbc.resultsettable: debug
    com.kep.portal.config.debug.DebugFilter: info


#Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**