spring:
  config:
    import:
      - optional:./portal-crane.yml
      - optional:./mysql-crane.yml

  security:
    debug: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    add-properties: true
  thymeleaf:
    cache: false

  cloud:
    discovery:
      client:
        simple:
          instances:
            platform-service:
              - uri: http://localhost:8080/platform
              - uri: http://127.0.0.1:8080/platform
            legacy-service:
              - uri: http://localhost:8080/legacy
              - uri: http://localhost:8080/legacy

  #mq, redis -> lookup dev third party server
  rabbitmq:
    host: 10.202.25.216
    port: 5672
    virtual-host: /${spring.application.name}
    username: ${spring.application.name}
    # TODO: encrypt
    password: portal!#%135
    connection-timeout: 3600000

  redis:
    host: 10.202.25.216
    port: 6379
    password: ${REDIS_PASSWORD:}
    cluster:
      nodes:

logging:
  pattern:
    file: '%(%d{yyyy-MM-dd HH:mm:ss} %30.30logger:%-4line) %-5level > %msg\n'
  file:
    path: ${LOGGING_PATH:/opt/storage/logs}/always/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  level:
    root: info
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    jdbc.sqlonly: debug
    jdbc.resultsettable: debug
    com.kep.portal.config.debug.DebugFilter: info

application:
  core:
    #    sync-client-id: 15a497d976ccf083f21572d0b1ff8111
    #로컬
    sync-client-id: 5c3a2963a9a33c85427b040b76d55c5b
