spring:
  config:
    import:
      - optional:./portal-sandbox.yml
      - optional:./mysql-sandbox.yml

  security:
    debug: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    add-properties: true
  thymeleaf:
    cache: false

  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false
        simple:
          instances:
            platform-service:
              - uri: http://platform-service:8080/platform
            talk-service:
              - uri: http://talk-service.talk:8080/talk

  #mq, redis -> lookup dev third party server
  rabbitmq:
    host: rabbitmq.rabbitmq.svc.cluster.local
    port: 5672
    virtual-host: /${spring.application.name}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    requested-heartbeat: 30
    connection-timeout: 3600000
    address-shuffle-mode: random

  redis:
    host: redis.redis.svc.cluster.local
    port: 6379
    password: ${REDIS_PASSWORD}
# prod 에선 master 3개로 cluster 설정 예정
#    cluster:
#      nodes:
#        - redis-node-0.redis.redis.svc.cluster.local:6379
#        - redis-node-1.redis.redis.svc.cluster.local:6379

logging:
  pattern:
    file: '%(%d{yyyy-MM-dd HH:mm:ss} %30.30logger:%-4line) %-5level > %msg\n'
  file:
    path: ${LOGGING_PATH:/opt/storage/logs}/always/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  level:
    root: info
    org.hibernate.SQL: info
    #    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: info
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    com.kep.portal.config.debug.DebugFilter: info

application:
  core:
    #    sync-client-id: 15a497d976ccf083f21572d0b1ff8111
    #로컬
    sync-client-id: 5c3a2963a9a33c85427b040b76d55c5b

#Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**