spring:
  config:
    import:
      - optional:./portal-kc-dev.yml
      - optional:./mysql-kc-dev.yml

  security:
    debug: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    add-properties: true
  thymeleaf:
    cache: false

  cloud:
    discovery:
      client:
        simple:
          instances:
            platform-service:
              - uri: http://localhost:8080/platform
            legacy-service:
              - uri: http://localhost:8080/legacy
  rabbitmq:
    addresses: 192.168.213.189:5672, 192.168.213.191:5672, 192.168.213.192:5672
    username: ${spring.application.name}
    password: portal!#%135
    connection-timeout: 3600000
    virtual-host: /${spring.application.name}
  redis:
    password: ${REDIS_PASSWORD:codeclick1213!}
    lettuce:
      pool:
        max-active: 8
    cluster:
      nodes:
        192.168.213.189:7398, 192.168.213.189:7498, 192.168.213.191:7398, 192.168.213.191:7498, 192.168.213.192:7398, 192.168.213.192:7498


logging:
  pattern:
    file: '%(%d{yyyy-MM-dd HH:mm:ss} %30.30logger:%-4line) %-5level > %msg\n'
  file:
    path: ${LOGGING_PATH:/opt/storage/logs}/kep-talk/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
  level:
    root: info
    #    org.hibernate.SQL: debug
    #    org.hibernate.type: trace
    #    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #    jdbc.sqlonly: debug
    #    jdbc.resultsettable: debug
    com.kep.portal.config.debug.DebugFilter: info
application:
  core:
    sync-client-id: 15a497d976ccf083f21572d0b1ff8111
    legacy-service-uri: http://rbsdev.bscap.co.kr