spring:
  datasource:
    url: jdbc:h2:tcp://${DB_URL:localhost:1521}/${DB_PATH:test};OLD_INFORMATION_SCHEMA=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS CONNECT_BRANCH\;SET SCHEMA CONNECT_BRANCH
    username: ${DB_USER:ENC(FtLBCHAdSAdacNSsXTcqIA==)}
#    username: ${DB_USER:sa}
    password: ${DB_PASSWD:}
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  sql:
    init:
      mode: never
      platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
#        hbm2dll:
#          create_namespaces: true
#        default_schema: kep_talk
#        globally_quoted_identifiers: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
  h2:
    console:
      enabled: false
      path: /h2-console
