spring:
  datasource:
    url: >-
      jdbc:mariadb://localhost:3306/kep_talk?
              autoReconnect=true&useSSL=false&useUnicode=true&allowMultiQueries=true
    username: ${DB_USER:kep_talk}
    password: ${DB_PASSWD:beerholic123!@#}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  sql:
    init:
      mode: never
      platform: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
#        hbm2dll:
#          create_namespaces: true
#        default_schema: kep_talk
        globally_quoted_identifiers: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
