spring:
  datasource:
    url: jdbc:mysql://always-test.mydev.onkakao.net:3306/always
    username: always
    password: Always23!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  sql:
    init:
      mode: never
      platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
#        hbm2dll:
#          create_namespaces: true
#        default_schema: kep_talk
        globally_quoted_identifiers: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
