spring:
  datasource:
    url: >-
      jdbc:oracle:thin:@
        (
          DESCRIPTION=
            (ADDRESS_LIST=
              (ADDRESS=(PROTOCOL=TCP)(HOST=database-1.csndvegemmbq.ap-northeast-2.rds.amazonaws.com)(PORT=1521))
            )
            (CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ORCL))
        )
    username: ${DB_USER:connect_branch}
#    username: ${DB_USER:kep_talk}
    password: ${DB_PASSWD:beerholic123!@#}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5
  sql:
    init:
      mode: never
      platform: oracle
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
#        hbm2dll:
#          create_namespaces: false
#        default_schema: kep_talk
#        globally_quoted_identifiers: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
