application:
  portal:
    api-version: 1
    api-base-path: /api/v${application.portal.api-version}
    service-url: https://always-talk.kakaoiconnect.ai
    service-domain: always-talk.kakaoiconnect.ai
    # upload
    storage-path: ${STORAGE_PATH:/opt/storage}
    upload-path: ${application.portal.storage-path}/upload
    upload-url: ${application.portal.service-url}/upload
    allowed-extension:
      - ".xlsx"
      - ".jpg"
      - ".jpeg"
    system-member-id: 9000000001
    kakao-bot-member-id: 9000000002
    # TODO : 실 사용 시 점심시간 변경 필요
    break-time-start: "21:00"
    break-time-end: "22:00"
    # FIXME : 인증 URL 변경 필요
    bnk-kakao-talk-url: https://always-talk.kakaoiconnect.ai/platform/auth/kakao-sync/getSync?state=
    dashboad:
      search-interval-minutes: 60
      batch-cron: 5 0/10 * * * *
      #FIXME : local 동일하게 추가 20240719 volka
      data-interval-minutes: 10
    # redis mode
    redis-mode: ${REDIS_MODE:standalone}
    # download
    download-api-url: https://always-talk.kakaoiconnect.ai/portal/api/v1/download
    evaluation-link-url : https://forms.gle/nRqDiAkKV7RmRwgs9
    # 친구톡 발송 불가 시간 (카카오 스펙) 추가 volka
    friend-talk-enable-start-time: "08:00"
    friend-talk-enable-end-time: "20:50"
  customer:
    api-version: 1
    api-base-path: /api/v${application.customer.api-version}
  platform:
    api-version: 1
    #FIXME :: api-base-path :: platform에서 리스닝 컨트롤러 path 20240719 volka
    api-base-path: /api/v1/counsel-portal
    #    api-base-path: /api/v1/portal
    #    api-key-name: X-API-Key
    api-key-name: Authorization
    api-key-method: APIKey
    message-path: /message
    close-path: /close
    relay-path: /relay
    redis-mode: ${REDIS_MODE:standalone}
  talk:
    api-version: 2
    api-base-path: /api/v${application.talk.api-version}
  socket:
    endpoint: /${spring.application.name}-ws
    general-path: /topic/general
    direct-path: /topic/direct
    branch-path: /topic/branch
    manager-path: /topic/manager
    admin-path: /topic/admin
    manager-admin-path: /topic/manager-admin
    issue-path: /topic/issue
    notice-path: /topic/notice
    upload-path: /topic/upload
    message-broker:
      host: rabbitmq.rabbitmq.svc.cluster.local
      port: 61613
      virtual-host: /${spring.application.name}
      username: ${RABBITMQ_USERNAME:admin}
      password: ${RABBITMQ_PASSWORD:Dlzpdk123!@}
      heartbeat-interval: 5000