application:
#  core:
#    internal-service-host: internal-service
#    servers:
#      -
#        id: 001
#        host: localhost
#        port: 8080
#      -
#        id: 002
#        host: 127.0.0.1
#        port: 8080
  portal:
    api-version: 1
    api-base-path: /api/v${application.portal.api-version}
    service-url: https://always-talk.kakaoiconnect.ai
    service-domain: always-talk.kakaoiconnect.ai
    # upload
    storage-path: ${STORAGE_PATH:/opt/storage}
    upload-path: ${application.portal.storage-path}/upload
    upload-url: ${application.portal.service-url}/upload
    #TODO :: 파일 허용 확장자 요건 정해지면 추가 20240717 volka
    allcate-extension:
      - ".xlsx"
      - ".jpg"
      - ".jpeg"
    system-member-id: 9000000001
    kakao-bot-member-id: 9000000002
    #FIXME :: breakTime 고정인지? 설정 가능할텐데 20240719 volka
    #eddie.j breakTime 임시 변경 ( 테스트 기간 동안 )
    break-time-start: "21:00"
    break-time-end: "22:00"
    #BNK  유입경로 FIXME :: bnk 설정
    bnk-kakao-talk-url: https://yocodeclick.loca.lt/platform/auth/kakao-sync/getSync?state=
    dashboad:
      search-interval-minutes: 60
      batch-cron: 5 0/10 * * * *
      #FIXME : local 동일하게 추가 20240719 volka
      data-interval-minutes: 10
    # redis mode
    redis-mode: ${REDIS_MODE:standalone}
    # eddie.j download api url 추가
    # download
    download-api-url : /portal/api/v1/download
  customer:
    api-version: 1
    api-base-path: /api/v${application.customer.api-version}
  platform:
    api-version: 1
    #FIXME :: api-base-path :: platform에서 리스닝 컨트롤러 path 20240719 volka
    api-base-path: /api/v1/counsel-portal
#    api-base-path: /api/v1/portal
#    api-key-name: X-API-Key
    api-key-name: Authorization
    api-key-method: APIKey
    message-path: /message
    close-path: /close
    relay-path: /relay
    redis-mode: ${REDIS_MODE:standalone}
  socket:
    endpoint: /${spring.application.name}-ws
    general-path: /topic/general
    direct-path: /topic/direct
    branch-path: /topic/branch
    manager-path: /topic/manager
    admin-path: /topic/admin
    manager-admin-path: /topic/manager-admin
    issue-path: /topic/issue
    message-broker:
      host: 10.206.16.58
      port: 61613
      virtual-host: /${spring.application.name}
      username: ${spring.application.name}
      # TODO: encrypt
      password: portal!#%135
      heartbeat-interval: 5000

#
#server:
#  servlet:
#    session:
#      cookie:
#        path: /
#        domain: codeclick.co.kr
