system-message:
  #채널 시스템 메세지 default
  channel:
    impossible:
      message: 죄송합니다. 현재 원활한 상담이 어렵습니다. 추후에 다시 이용 부탁드립니다.
    assign-standby:
      message: 죄송합니다. 현재 먼저 접수된 상담이 많아 채팅상담이 지연되고 있습니다. 잠시 후 다시 이용 부탁드립니다.
    evaluation:
      message: 상담에 만족하셨나요? 상담품질 개선을 위해 만족도 평가를 부탁드립니다^^
    start:
      st:
        code: ST
        message: 1:1채팅을 요청하셨습니다. 채팅 내용은 상담 품질 관리를 위해 '#{위탁사명}'에 저장됩니다. 상담을 시작하려면 메시지를 입력해주세요. 채팅을 원치 않으시면 "!종료"를 입력해주세요.(카톡)
      #상담시작 공통 인사말
      welcom: 사랑하는 고객님 반갑습니다. 상담직원 {{상담직원명}} 입니다. 무엇을 도와드릴까요?
      #배정대기(상담접수) 안내 [S1 상담불가]
      unable:
        code: S1
        message: 상담원 연결이 지연되고 있습니다. 잠시 후 다시 이용해 주세요.(훌쩍)
      #배정대기/상담대기 안내 [S2 상담부재]
      absence:
        code: S2
        message: 지금은 상담 가능 시간이 아닙니다.(깜짝)
      # [S3 무응답 종료]
      no-response-end:
        code: S3
        message: 일정 시간 동안 고객님의 응답이 없어 채팅을 종료합니다.(우와)
      #상담대기 안내 [S4 상담대기]
      waiting:
        code: S4
        message: 상담원 연결 대기 중입니다. 잠시만 기다려 주세요.(제발)
      #상담 불가 안내
      impossible: 죄송합니다. 현재 원활한 상담이 어렵습니다. 추후에 다시 이용 부탁드립니다.
      #배정대기 건수 제한
      assign-standby: 죄송합니다. 현재 먼저 접수된 상담이 많아 채팅상담이 지연되고 있습니다. 잠시 후 다시 이용 부탁드립니다.
    end:
      #근무 외 시간 상담 접수 사용
      register: 현재는 상담직원 응대가 어렵습니다. 근무시간에 다시 문의해주세요.
      #상담대기 중 상담직원응답 지연 안내
      member-delay: 고객님 죄송합니다. 현재는 상담직원 응대가 어렵습니다. \n 상담이 가능할 때 즉시 상담 도와드릴 예정이니 종료하지말고 기다려주세요!
      #고객응답 지연 자동종료 사용
      guest-delay: 고객님 말씀이 없으셔서 다음 상담을 위해 상담을 종료합니다. 궁금하신 내용이 생기시면 언제든 다시 문의주시기 바라며,오늘도 행복한 하루되세요^^
      #고객응답 지연 자동종료 예고 사용
      guest-notice-delay: 추가 문의가 없으시면 5분 뒤 상담이 자동 종료됩니다. 궁금하신 내용이 있으시면 말씀해주세요~
      #상담종료 안내
      guide:
        message: 추가 문의가 없으신가요? 즉시 상담을 종료하시려면 아래 ‘!종료’ 버튼을 눌러주세요.
        notice-message: 고객님 말씀이 없으셔서 다음 상담을 위해 상담을 종료합니다. 궁금하신 내용이 생기시면 언제든 다시 문의주시기 바라며, 오늘도 행복한 하루되세요^^

  portal:
    notification:
      title-message:
        delay-issue-room: ${상담고객}님에게 온 메시지에 ${m}분이상 답을 하지 않고 있습니다.
        done-member-assignment: 상담직원 배정이 완료되었습니다. 상담고객을 확인해주세요.
        request-member-transform: ${요청 상담직원}님의 상담직원 전환이 요청되었습니다.
        done-member-transform: ${상담고객}님의 상담직원 전환이 완료되었습니다.
        refer-member-transform: ${상담고객}님의 상담직원 전환이 반려되었습니다.
        fail-manual-member-transform: ${요청 상담직원}님의 상담직원 전환이 실패되었습니다.
        fail-auto-member-transform: ${상담고객}님의 상담직원 전환이 실패되었습니다.
        request-review-counselling-details: ${요청 상담직원}님의 상담내용 검토가 요청되었습니다.
        done-review-counselling-details: ${상담고객}님의 상담내용 검토가 완료되었습니다.
        refer-review-counselling-details: ${상담고객}님의 상담내용 검토가 반려되었습니다.
        done-consultation-transfer: ${상담고객}님의 상담이 담당매니저에게 이관되었습니다.
        fail-consultation-transfer: ${상담고객}님의 상담 이관이 실패되었습니다. 상담 가능 상태를 확인해주세요.
        end-counsel: ${상담고객}님의 상담이 담당 매니저에 의해 종료되었습니다.
        notice: 새로운 공지사항이 등록되었습니다.
        talk-request-approve: ${요청 상담직원}님의 톡 발송 승인이 요청되었습니다.
        talk-approve: 톡 발송이 승인되었습니다.
        talk-reject: 톡 발송이 반려되었습니다.
        expired-by-duplication: 다른 환경에서 로그인되어 현재 사용 중인 환경에서 로그아웃 되었습니다.

    login:
      login-failed-message:
        bad-credentials: 아이디 또는 비밀번호가 일치하지 않습니다. 다시 확인해 주세요.
        disabled: 로그인이 불가능한 계정입니다. 관리자에게 문의해주세요.
       
#       2023.09.14/YO/ 유저가 존재하지 않을 시
        user-not-found: "유저를 찾을 수 없습니다."
#       2023.09.14/YO/ 동일 계정으로 접속시 에러문구 추가
        already-account-logged-in: "이미 로그인된 계정입니다."    
#       2023.09.15/YO/ 세션 유효시간 설정 추가
        expired-message: "세션이 만료되었습니다. 다시 로그인해주세요."
       
    password:
      change-message:
        not-match: 현재 비밀번호가 올바르지 않습니다. 다시 확인해주세요.
        not-password-rule: 비밀번호는 10~16자의 영문 대소문자와 숫자, 특수문자 중 2가지를 혼합하여 사용할 수 있습니다.
        not-equal-confirm: 새 비밀번호와 새 비밀번호 확인이 일치하지 않습니다.
        not-safety: 안전도가 너무 낮습니다. 동일한 문자를 연속으로 3자리 이상 설정이 불가합니다.

  consultation-talk:
    button:
      close: "!종료"
      evaluation: 상담평가하기

  # 시스템 설정 > 상담 설정 > 상담 환경 설정
  consultation-environment-settings:
    validation:
      consultation-funnel: 해당 변수명은 이미 존재하거나 삭제된 상태입니다. 다른 이름으로 저장해주세요.