name: Build & Push portal

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "SPRING_PROFILES_ACTIVE"
        required: true
        default: "sandbox"

env:
  # Docker Hub
  DOCKERHUB_NAMESPACE: timulys # ex) timulys (Repo → Settings → Variables에 등록)
  IMAGE_NAME: portal
  # Dockerfile build-args
  MODULE: portal
  ENVIRONMENT: ${{ github.event.inputs.environment || 'sandbox' }}
  VALUES_FILE: helm/always/values.yaml       # values.yaml 경로

jobs:
  build-and-push-portal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}
          flavor: latest=false
          tags: |
            type=sha,format=short,prefix=portal-

      - name: Build & Push (portal)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            MODULE=${{ env.MODULE }}
            ENVIRONMENT=${{ env.ENVIRONMENT }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: false
          provenance: false

      # values.yaml 의 apps[0] (portal) 이미지 태그만 최신으로 교체
      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Bump image tag in values.yaml
        run: |
          NEW_TAG="${{ steps.meta.outputs.version }}"  # e.g. portal-abcdef0
          yq -i '.apps[0].image.tag = strenv(NEW_TAG)' "${{ env.VALUES_FILE }}"
          echo "New tag set to: ${NEW_TAG}"
          git diff -- "${{ env.VALUES_FILE }}"

      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ env.VALUES_FILE }}"
          git commit -m "chore(portal): bump image tag to ${{ steps.meta.outputs.version }}" || echo "No changes to commit"
          git push
