name: Build & Push talk

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "SPRING_PROFILES_ACTIVE"
        required: true
        default: "sandbox"

env:
  # Docker Hub
  DOCKERHUB_NAMESPACE: timulys # ex) timulys (Repo → Settings → Variables에 등록)
  IMAGE_NAME: talk

  # Dockerfile build-args
  MODULE: talk
  ENVIRONMENT: ${{ github.event.inputs.environment || 'sandbox' }}

jobs:
  build-and-push-talk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}
          flavor: latest=false
          tags: |
            type=sha,format=short,prefix=portal-

      - name: Build & Push (talk)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            MODULE=${{ env.MODULE }}
            ENVIRONMENT=${{ env.ENVIRONMENT }}
            MAVEN_IMAGE=maven:3.9.6-eclipse-temurin-17
            TOMCAT_IMAGE=tomcat:9.0-jdk17-temurin
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: false
          provenance: false
